apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      name: http
      port: 4295
    - protocol: TCP
      name: grpc
      port: 5295

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: docker.rikarin.org/cord/orion
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/config.yaml
              name: config
              subPath: config.yaml
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4295
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4295
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: config
          configMap:
            name: cord-config
